### ISSUE TITLE
多整点二次元

### ISSUE THREAD

**Issue by RitaRossweiss** [1123Javayanglei/macBackground#1]

**Comment by 1123Javayanglei** [comment]
github难搞，我项目迁移到码云了，一键导入所有github项目爽，git clone 10M/S，爽

**Comment by qieyuanwanhua** [comment]
> github难搞，我项目迁移到码云了，一键导入所有github项目爽，git clone 10M / S，爽

**码云也就网速快点，资源和有意思的项目还是比较少，小飞机SSR配合GitHub感觉速度也很快。**
